#ifndef EVENT_H
#define EVENT_H

enum CartEvent {
    CART_EVENT_ASSOCIATED,
    CART_EVENT_ASSIGNED,
    CART_EVENT_CASH_OUT,
    CART_EVENT_NEW_PRODUCT,
    CART_EVENT_CASH_OUT_ACK,
    CART_EVENT_CASH_OUT_PARTIAL_LIST_ACK
} event;

#endif
